# list of modules that shall be used during image creation.
# see module-configs below to configure the modules (if applicable)
modules:
    # debug mode: the initrds will be much larger and much more usable
    - debug
    # never disable those core components:
    - base
    - nbd
    ###########################################################################
    # select one of the following systems:
    # support for arch linux payload systems (mkinitcpio)
    #- system-arch
    # support for debian linux payload systems
    #- system-debian
    # support for gentoo+dracut payload systems
    #- system-gentoo
    ###########################################################################
    # optional components
    # your /boot or / device is on lvm
    - lvm
    # support for r8152-family realtek USB ethernet controllers
    #- r8152
    # support for clevo notebook fan control
    #- clevo-fancontrol

boot:
    # the disk that is shared by the server
    disk: /dev/disk/by-id/ata-SOME_RANDOM_DRIVE
    # the boot partition where the server gets the kernel and initrd
    part:
        # directly accessible boot partition block device
        type: plain
        block: /dev/disk/by-partlabel/boot

        # luks-encrypted boot partition
        #type: luks
        #luks_block: /dev/disk/by-uuid/e9aaxe22-8a07-4d0d-8c5f-b2b55ddc7cbb
        #block: /dev/lollvmvg/boot
    # the cmdline that will be given to the stiefeled system
    load:
        kernel: /boot/vmlinuz-linux
        initrd: /boot/initramfs-linux.img
        # cmdline that will be given to the stiefeled system
        # root has to be your real system's '/' filesystem
        cmdline:
            - root=UUID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
            - rw
            - consoleblank=0

# settings for automatic reboot of the laptop into stiefel-server
autokexec:
    broadcast: True
    mac_detection: False
    # you probably don't need this!
    # modern stiefelsystem has network discovery messages!
    #
    # if you want to reboot your system when one of these macs is
    # detected, enter the macs that should trigger here.
    # otherwise, use a valid but nonexisting mac.
    macs:
        - "11:11:11:11:11:11"

server-setup:
    # how to setup the system that boots the stiefelsystem server
    # the config json is always placed in /boot/stiefelsystem.json

    # the kernel of the stiefelsystem
    # both this kernel and the initrd are multi-purpose;
    # the same images are used when creating the client flash drive
    # and when kexec-ing into the server system.
    stiefelsystem-kernel: /var/local/lib/stiefelsystem/kernel
    # the initrd of the stiefelsystem
    stiefelsystem-initrd: /var/local/lib/stiefelsystem/initrd

    # kernel cmdline options for the stiefel-server kernel
    cmdline:
        - ro

# instructions for generating the initrd
initrd:
    # list of debian packages that shall be included
    include-packages:
        - iputils-ping

    shell: /usr/bin/dash
    password: stiefel

    # instructions for packing
    packing:
        # compression utility that is called for the initrd CPIO
        # use 'cat' for uncompressed CPIO
        compressor: pigz -11
        # these paths will not be included in the initrd CPIO archive
        # when packing it, to save space
        exclude-paths:
            - boot
            - usr/share/man
            - var/cache
            - var/lib/apt
            - var/lib/dpkg
            - var/log
            - usr/share/locale
            - usr/share/info
            - usr/share/doc
            - usr/share/zoneinfo
            - usr/share/bash-completion
            - usr/share/zsh
            - usr/share/initramfs-tools
            - usr/share/keyrings
            - usr/share/common-licenses
            - usr/lib/apt
            - usr/lib/dpkg
            - etc/apt
            - etc/dpkg
            - etc/motd
            - root
        # files that are included in these apt packages will not be included
        # the initrd CPIO archive when packing it, to save space
        exclude-packages:
            # we don't need no stinking package manager
            # dpkg is unfortunately required for /sbin/start-stop-daemon
            - apt
            - debconf
            - libapt-pkg5.0:amd64
            - libdebconfclient0:amd64
            # yay! our system is perl-free!
            - perl-base
            # utils
            - e2fsprogs
            - fdisk
            - passwd
            - adduser
            - findutils
            - hostname
            - sensible-utils  # don't seem very sensible to me!!!!!!!!111111
            - libext2fs2:amd64
            - libfdisk1:amd64
            # initramfs-generation stuff
            - initramfs-tools
            - initramfs-tools-core
            - cpio
            - libklibc:amd64
            - klibc-utils
            # not so sure about these...
            - ncurses-bin
            - libdb5.3:amd64
            - libsemanage-common
            - libsemanage1:amd64
            - libsepol1:amd64
            - libss2:amd64
            # who needs usability
            - bash
            - readline-common
            - libreadline7:amd64
            # haha who needs basic unix tools
            - grep
            - mawk
            - tar
            # this was just for running the nspawn commands during setup
            - systemd-container

# the directory structure where the temporary and other files
# will be placed while running these scripts.
paths:
    # cache folder; the ramdisk here persists over multiple iterations,
    # and e.g. caches debootstrap downloads.
    cache: cache

    # work directory; the ramdisk here is re-created when a new initcpio
    # is created.
    workdir: workdir

    # subdirectories of the workdir
    workdir-subpaths:
        # the target initrd CPIO archive
        cpio: initrd.cpio
        # the target initrd
        initrd: initrd.nspawn
        # the development overlayfs mount of the initrd, where compilers
        # are installed and run.
        initrd-devel: initrd.nspawn-devel

# module-specific options
module-configs:
    debug:
        better-shell: /usr/bin/bash
        dont-exclude-packages: true
        dont-exclude-paths: true
        faster-compressor: pigz -1
        extra-packages:
            - bash-completion
            - curl
            - ethtool
            - gzip
            - htop
            - iperf
            - less
            - man-db
            - mlocate
            - nbd-client
            - neovim
            - nmap
            - pciutils
            - pigz
            - procps
            - psmisc
            - pv
            - silversearcher-ag
            - tcpdump
            - time
            - tmux
            - usbutils
            - util-linux
            - xxd
            - xz-utils
    r8152:
        url: https://github.com/wget/realtek-r8152-linux/archive/v2.13.tar.gz
    clevo-fancontrol:
        url: https://github.com/mic-e/clevo-fancontrol/archive/1.0.tar.gz
