#!/bin/bash

run_hook() {
    echo 'waiting for stiefelsystem ethernet device...'

    pushd /sys/class/net/
    local i=0
    while [ ! -d stiefellink ]; do
        local renamed=n
        for iface in "*"; do
            if [ `cat "$iface/address"` == "${stiefel_link}" ]; then
                ip link set name stiefellink dev "$iface" && { renamed=y; break; }
            fi
        done
        i=$(($i+1))
        [ $i -eq 200 ] && {
            msg "could not find interface ${stiefel_link} :("
            return 1
        }
        [ renamed == 'n' ] && sleep 0.1
    done
    popd

    ip link set up stiefellink

    echo "waiting for stiefel-server to be reachable..."
    i=0
    while true; do
        if ping -w1 -c1 ${stiefel_nbdhost}; then
            break
        else
            sleep 0.1
        fi
        i=$(($i+1))
        [ $i -eq 200 ] && {
            msg "could not ping ${stiefel_nbdhost} :("
            return 1
        }
    done

    modprobe nbd
    msg "mapping stiefelsystem nbd..."
    cmd=nbd-client ${stiefel_nbdhost} /dev/nbd0 -systemd-mark -persist -name ${stiefel_nbdname}
    msg "$cmd"
    $cmd || return 1
    msg "stiefelsystem nbd devices mapped."
    blkid
}
