#!/bin/sh
PREREQ=""
prereqs()
{
     echo "$PREREQ"
}

case $1 in
prereqs)
     prereqs
     exit 0
     ;;
esac

# ifrename
. /usr/share/initramfs-tools/hook-functions #provides copy_exec
rm -f ${DESTDIR}/bin/wg
copy_exec /usr/bin/wg /bin/wg #Takes location in filesystem and location in initramfs as arguments
