#!/bin/sh

# ifname=stiefellink:MAC ip=stiefellink:link6 
# wg_privkey=privatekey wg_endpoint=server:port wg_pubkey=pubkey
# [root=*] netroot=nbd:srv:port/exportname[:fstype[:rootflags[:nbdopts]]]

run_hook() {

case "$(cat /proc/cmdline)" in
  *stiefel*)
    echo "we are beeing stiefeled"
	;;
	*)
	  exit 1
	;;
esac

for x in $(cat /proc/cmdline); do
  case "$x" in
    ifname=*)
      MAC=${x#ifname=stiefellink:}
      ;;
    wg_privkey=*)
      wg_privkey=${x#wg_privkey=}
      ;;
    wg_endpoint=*)
      wg_endpoint=${x#wg_endpoint=}
      ;;
    wg_pubkey=*)
      wg_pubkey=${x#wg_pubkey=}
      ;;
    netroot=*)
      netroot=${x#netroot=}
      ;;
  esac
done

nroot=${netroot#nbd:}

nbdserver=${nroot%%:*}
if [ "${nbdserver%"${nbdserver#?}"}" = "[" ]; then
  nbdserver=${nroot#[}
  nbdserver=${nbdserver%%]:*}
  nroot=${nroot#*]:}
else
  nroot=${nroot#*:}
fi
nbdport=${nroot%%:*}
nroot=${nroot#*:}
nbdfstype=${nroot%%:*}
nroot=${nroot#*:}
rootflags=${nroot%%:*}
nroot=${nroot#*:}
nbdflags=${nroot%%:*}

if [ "$nbdflags" = "$rootflags" ]; then
    unset nbdflags
fi
if [ "$rootflags" = "$nbdfstype" ]; then
    unset rootflags
fi
if [ "$nbdfstype" = "$nbdport" ]; then
    unset nbdfstype
fi

wgserver=${wg_endpoint#[}
wgserver=${wgserver%%]:*}
wgport=${wg_endpoint##*:}

if ! [ "$nbdport" -gt 0 ] 2> /dev/null; then
  nbdport="-name $nbdport"
fi

echo 'waiting for ethernet device'

i=0
while [ $i -lt 1000 ]; do
  # attempt to rename. the command gives no feedback :(
  echo "stiefellink mac $MAC" | ifrename -c -

  if [ -e /sys/class/net/stiefellink ]; then
    break
  fi
  sleep 0.05
  i=$(($i+1))
done

if [ $i == 1000 ]; then
  echo "Failed to setup interface"
  exit 1
fi

ip link set up stiefellink

echo "waiting for server to be reachable"

i=0
while [ $i -lt 500 ]; do
  if ping -w1 -c1 $wgserver; then
    break
  fi
  sleep 0.1
  i=$(($i+1))
done

if [ $i == 500 ]; then
  echo "Failed to reach wireguard server at $wgserver on port $wgport"
  exit 1
fi

ip link add dev wgstiefel type wireguard

if [ -f /etc/wireguard/stiefel.conf ]; then
  wg setconf wgstiefel /etc/wireguard/wgstiefel.conf
else
  echo "$wg_privkey" > /privkey
  wg set wgstiefel private-key /privkey
  wg set wgstiefel peer "$wg_pubkey" allowed-ips fe80::/64 endpoint "$wg_endpoint"
fi

ip addr add fe80::2/64 dev wgstiefel
ip link set wgstiefel up
ip a

echo "waiting for server to be reachable"

i=0
while [ $i -lt 30 ]; do
  if ping -w1 -c1 $nbdserver; then
    break
  fi
  sleep 0.1
  i=$(($i+1))
done

if [ $i == 30 ]; then
  echo "Failed to reach nbd server at $nbdserver via wireguard"
  exit 1
fi

echo "modprobe nbd"
modprobe nbd
echo "nbd-client $nbdserver /dev/nbd0 -systemd-mark -persist $nbdport $nbdflags"
nbd-client "$nbdserver" /dev/nbd0 -systemd-mark -persist $nbdport $nbdflags
echo "nbd mount done"
blkid
}
